"""empty message

Revision ID: 334dc099bf45
Revises: d67870c24591
Create Date: 2022-08-28 13:58:33.333004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334dc099bf45'
down_revision = 'd67870c24591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('mobile', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_mobile'), 'user', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mobile'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
