"""empty message

Revision ID: 4185653e0a0d
Revises: 
Create Date: 2022-08-27 13:02:33.029264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4185653e0a0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_stop', sa.Date(), nullable=True),
    sa.Column('booked_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booked_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('period')
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('mail', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('forename', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('surename', sa.String(length=64), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_user_forename'), 'user', ['forename'], unique=False)
    op.create_index(op.f('ix_user_mail'), 'user', ['mail'], unique=True)
    op.create_index(op.f('ix_user_surename'), 'user', ['surename'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('email', mysql.CHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surename'), table_name='user')
    op.drop_index(op.f('ix_user_mail'), table_name='user')
    op.drop_index(op.f('ix_user_forename'), table_name='user')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'surename')
    op.drop_column('user', 'forename')
    op.drop_column('user', 'mail')
    op.drop_column('user', 'password_hash')
    op.create_table('period',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('begin', sa.DATE(), nullable=True),
    sa.Column('end', sa.DATE(), nullable=True),
    sa.Column('reserved_user', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reserved_user'], ['user.id'], name='period_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('timeslot')
    # ### end Alembic commands ###
