"""empty message

Revision ID: 5549c8107caa
Revises: dab49475c020
Create Date: 2022-08-28 09:22:53.733431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5549c8107caa'
down_revision = 'dab49475c020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_mail', table_name='user')
    op.drop_column('user', 'mail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_mail', 'user', ['mail'], unique=False)
    # ### end Alembic commands ###
