"""empty message

Revision ID: 64ccaf8cc357
Revises: c3a9a326d763
Create Date: 2022-08-28 08:50:43.338004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64ccaf8cc357'
down_revision = 'c3a9a326d763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('timeslot', sa.Column('date_stop', sa.Date(), nullable=True))
    op.add_column('timeslot', sa.Column('booked_user', sa.Integer(), nullable=True))
    op.drop_constraint('timeslot_ibfk_1', 'timeslot', type_='foreignkey')
    op.create_foreign_key(None, 'timeslot', 'user', ['booked_user'], ['id'])
    op.drop_column('timeslot', 'bis')
    op.drop_column('timeslot', 'von')
    op.drop_column('timeslot', 'reserviert_von')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('reserviert_von', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timeslot', sa.Column('von', sa.DATE(), nullable=True))
    op.add_column('timeslot', sa.Column('bis', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'timeslot', type_='foreignkey')
    op.create_foreign_key('timeslot_ibfk_1', 'timeslot', 'user', ['reserviert_von'], ['id'])
    op.drop_column('timeslot', 'booked_user')
    op.drop_column('timeslot', 'date_stop')
    op.drop_column('timeslot', 'date_start')
    # ### end Alembic commands ###
