"""'timeslot'

Revision ID: c3a9a326d763
Revises: 4185653e0a0d
Create Date: 2022-08-27 13:51:06.422897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3a9a326d763'
down_revision = '4185653e0a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('von', sa.Date(), nullable=True))
    op.add_column('timeslot', sa.Column('bis', sa.Date(), nullable=True))
    op.add_column('timeslot', sa.Column('reserviert_von', sa.Integer(), nullable=True))
    op.drop_constraint('timeslot_ibfk_1', 'timeslot', type_='foreignkey')
    op.create_foreign_key(None, 'timeslot', 'user', ['reserviert_von'], ['id'])
    op.drop_column('timeslot', 'date_start')
    op.drop_column('timeslot', 'date_stop')
    op.drop_column('timeslot', 'booked_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('booked_user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('timeslot', sa.Column('date_stop', sa.DATE(), nullable=True))
    op.add_column('timeslot', sa.Column('date_start', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'timeslot', type_='foreignkey')
    op.create_foreign_key('timeslot_ibfk_1', 'timeslot', 'user', ['booked_user'], ['id'])
    op.drop_column('timeslot', 'reserviert_von')
    op.drop_column('timeslot', 'bis')
    op.drop_column('timeslot', 'von')
    # ### end Alembic commands ###
